export const getList = () => {
    return [
        {
            book_action: ' 宜据理力争 ',
            book_love: ' 双方逞强，宜多加沟通迁就',
            book_lose: ' 可望寻回',
            book_means: ' 困龙得水好运交，不由喜气上眉梢 一切谋望皆如意，向后时运渐渐高 ',
            book_all: ' 天行刚健，自强不息',
            book_disease: ' 病情恶化，宜细心调养，注意头，脑，骨髓等病变',
            book_code: '111111',
            book_name: '乾卦',
            book_introduc: '困龙得水 上上卦 ',
            book_lucky: ' 飞龙在天，名利双名之象，宜把握机会，争取成果',
            id: 12,
            book_sort: '1',
            book_remark: '乾上乾下凛凛皇者之象 自强不息之意。',
            book_result: ' 词讼和吉，病人痊愈，功名有成，求名大吉',
        },
        {
            book_action: ' 防房地产之争，宜和解，有始无终之兆',
            book_love: ' 急进有失，缓进反成，欲速不达',
            book_lose: ' 难以寻回，大部份均不知下落',
            book_means: '饿虎得食喜气欢，求名应事主高迁 出门吉利行人到，是非口舌不相干 ',
            book_all: ' 大地承载万物，以德服众，仁者无敌',
            book_disease: ' 病情严重，为腹，肠胃，肌肉等慢性病',
            book_code: '000000',
            book_name: '坤卦',
            book_introduc: '饿虎得食，上中卦 ',
            book_lucky: ' 诸事不宜急进，以静制动为宜',
            id: 13,
            book_sort: '2',
            book_remark: '坤为地，坤上坤下兼空万物之象，以柔克刚之意。',
            book_result: ' 找人得见，走失有信，疾病见好，凡事皆顺 ',
        },
        {
            book_action: ' 小事粘滞纠缠，大事反无大害，宜和解',
            book_love: ' 感情发展受阻 宜坚守信念，排除困难',
            book_lose: ' 难以寻回',
            book_means: ' 风刮乱丝不见头，颠三倒四犯忧愁，慢行缓来头有绪，急促反惹不自由',
            book_all: ' 屯者难也，万事欲进而不得进',
            book_disease: ' 病在肠胃，足部或泌尿系统，不宜掉以轻心',
            book_code: '010001',
            book_name: '屯',
            book_introduc: '乱丝无头，下下卦 ',
            book_lucky: ' 身处困境，步步为营，有初难后解之意',
            id: 14,
            book_sort: '3',
            book_remark: '水雷屯 坎上震下 春木更新之象 艰难险阻之意',
            book_result: ' 疾病未好，婚姻不巧，口舌琐碎，做事颠倒',
        },
        {
            book_action: ' 因外人引起事端，目下未明，有理讲不清 ',
            book_love: ' 落花有意流水无情，主缺乏勇气与决心',
            book_lose: ' 遍寻不获，似乎在大门下陷之处遗失，忘记带走，可试问人',
            book_means: ' 卦中气象犯小耗 谋望求财枉徒劳婚姻合伙有人破，交易出行犯唠叨',
            book_all: ' 蒙者，昏而无所见也，故宜 启蒙 ',
            book_disease: ' 病情不明，反覆难治，为肠胃 腹水之疾及传染病',
            book_code: '100010',
            book_name: '蒙',
            book_introduc: '小鬼偷钱 中下卦',
            book_lucky: ' 初时迷惑不知方向，须忍耐待机而动，凡事多听取别人的意见则运可通',
            id: 15,
            book_sort: '4',
            book_remark: '山水蒙 艮上坎下 童蒙启智之象 迷模摸索之意',
            book_result: ' 为人仔细，挣钱费力，有心学好，小鬼偷去',
        },
        {
            book_action: ' 暂时未能了结，以和为贵',
            book_love: ' 感情发展初期不如意，必须耐心等待，方见有成',
            book_lose: ' 即时不能寻回，需经过一段时间将会出现',
            book_means: ' 明珠出土埋久深，无光无毫到如今 忽然大风吹去土，自然显露又重新',
            book_all: ' 云登天上而未雨，不能急进，等待时机之象',
            book_disease: ' 病情拖延，须留心治疗，为头胸，泌尿系统等病',
            book_code: '010111',
            book_name: '需',
            book_introduc: '明珠出土 上上卦',
            book_lucky: ' 智者必须待时而行，急进反见凶险',
            id: 16,
            book_sort: '5',
            book_remark: '水天需 坎上乾下 密去不雨之象 待机而动之意',
            book_result: ' 谋望有成，婚姻最合，求财如意，也喜动挪',
        },
        {
            book_action: ' 两败俱伤，宜找中间人调解，久争无益',
            book_love: ' 反覆不定 是非频频，更防小人破坏',
            book_lose: ' 不会出现',
            book_means: ' 二人争路未肯降，占着此卦费主张，交易出行有阻隔，生意合伙有平常',
            book_all: ' 乾天升于上，坎水降于下，相背而行起讼',
            book_disease: ' 病情严重，为腰，血液，泌尿系统，头部疾患',
            book_name: '讼',
            book_introduc: '二人争路，平平卦',
            book_lucky: ' 事与愿违，凡事不顺，小人加害 宜防陷阱',
            id: 17,
            book_sort: '6',
            book_remark: '天水讼 乾上坎下 背道而驰之象，无端起讼之意',
            book_result: ' 月令不济，光生闲气 好事难成，求财费力',
        },
        {
            book_action: ' 宜进不宜退，内心虽忧，但得贵人之助',
            book_love: ' 阴盛阳衰，须提防色情之厄，似多角关系，求婚难成',
            book_lose: ' 不会出现 即或寻回，也已损坏',
            book_means: ' 将帅领旨去出征，骑着烈马拉硬弓，百步穿杨去的准，箭射金钱喜气生',
            book_all: ' 养兵聚众，出师攻伐之象，彼此有伤，难得安宁',
            book_disease: ' 病况严重，提防心脏或腹腔肿瘤等',
            book_code: '',
            book_name: '师',
            book_introduc: '马到成功 上平卦',
            book_lucky: ' 困难重重，凡事以正规行事，忌独断独行，投机取巧，提防潜在敌人',
            id: 18,
            book_sort: '7',
            book_remark: '地水师 坤上坎下 地势临渊之象 以寡服众之意',
            book_result: ' 疾病大好，走失能找 行人有信，百事凑巧',
        },
        {
            book_action: ' 宜以和解态度面对，虽小人多，但可胜诉',
            book_love: ' 两情相悦，美好良缘',
            book_lose: ' 不会再现，通常均已遭损毁',
            book_means: ' 顺风行船撒起棚，上天又助一篷风，不用费力逍遥去 任意而行大亨通',
            book_all: ' 一阳统五阴，比邻相亲相辅，和乐之象',
            book_disease: ' 新病宜速就医，久病则危，为腹，肾，耳等疾',
            book_name: '比',
            book_introduc: '船得顺风 上吉卦',
            book_lucky: ' 平顺可得贵人提拔，凡事宜速战速决，不可过份迟疑',
            id: 19,
            book_sort: '8',
            book_remark: '水地比 坎上坤下 众星拱月这象 安逸进取之意',
            book_result: ' 走失可寻，见官有理，婚姻求名，保管恭喜',
        },
        {
            book_action: ' 会因证据不足而败诉',
            book_love: ' 意见分歧，或遭受长辈反对',
            book_lose: ' 似乎遗失的是金器或现金支票等物，有被硬物夹住，或者第三格的地方',
            book_means: ' 浓云密排下雨难 盼望行人不见还交易出行空费力 婚姻求谋是枉然',
            book_all: ' 蓄养之量有限，力不从心 故宜忍耐蓄养实力，静待时机',
            book_disease: ' 危 重病 注意肝，头部病变',
            book_name: '小畜',
            book_introduc: '密云不雨 下平卦',
            book_lucky: ' 运势反覆，有口舌之争，但难于短期内解决，须忍耐，静待时机',
            id: 20,
            book_sort: '9',
            book_remark: '风天小畜 巽上乾下 密云无雨之象 蓄养实力之意',
            book_result: ' 月令中平，忍耐从容，疾病口舌，交节安宁',
        },
        {
            book_action: ' 敌强而我弱之象 宜步步为营',
            book_love: ' 两情相悦 但阻碍重重，精诚所至 金石为开',
            book_lose: ' 赶快去找有可能寻回，留意行过的路上，或者有鞋的地方',
            book_means: ' 俊鸟幸得出笼中 脱离灾难显威风一朝得志凌云去 东南西北任意行',
            book_all: ' 柔弱遇刚强 欲行却难行之象难且危',
            book_disease: ' 病虽重 但注意调理亦可愈防头 口 肺等疾',
            book_name: '履',
            book_introduc: '俊鸟出笼 中吉卦',
            book_lucky: ' 先劳而后逸，始惊而后安 百事不宜急进 须以和待人 有惊无险',
            id: 21,
            book_sort: '10',
            book_remark: '天泽履 乾上兑下 如履虎尾之象 险中求胜之意',
            book_result: ' 合伙如意 迁移如心 买卖兴旺求财十分',
        },
        {
            book_action: ' 是非由小事化大，终可和解',
            book_love: ' 情投意合 良缘缔结',
            book_lose: ' 不会出现',
            book_means: ' 喜报三元运气强，谋望求财大吉祥 交易出行多得意，是非口舌总无防',
            book_all: ' 天地阴阳之气相交感 上下和睦流通无阻',
            book_disease: ' 久病不利，注意肠肺及头部之症',
            book_name: '泰',
            book_introduc: '喜报三元 上吉卦',
            book_lucky: ' 诸事吉祥顺利，凡事宜内求，不宜外求，防乐极生悲',
            id: 22,
            book_sort: '11',
            book_remark: '地天泰 坤上乾下 事事通泰之象 上下和睦之意',
            book_result: ' 婚姻有成 行人即至 失物可寻诸般凑巧',
        },
        {
            book_action: ' 各走极端 有口难言 宜及时求和',
            book_love: ' 阴阳相背 拒人千里之外 有不和及离别之象',
            book_lose: ' 寻不回',
            book_means: ' 虎落陷坑不堪言 前进容易退后难谋望不遂自已便 疾病口舌有牵连',
            book_all: ' 天气上升 地气下降 天地这气不交主闭塞不通',
            book_disease: ' 占病为凶兆，病在脑 肺及肠胃等 慎防癌症',
            book_name: '否',
            book_introduc: '虎落陷坑 下平卦',
            book_lucky: ' 上下不和 百事不通 凡事宜忍须知否极泰来',
            id: 23,
            book_sort: '12',
            book_remark: '天地否 乾上坤下 闭塞不通之象 上下不和之意',
            book_result: ' 占财可成 贵人远行 出行不宜事事晚成',
        },
        {
            book_action: ' 凡事以和为贵',
            book_love: ' 如鱼得水 彼此互敬互凉，定成美眷',
            book_lose: ' 遗失似文件眼镜等物，可能被压在底层，尽快寻找，则可取回',
            book_means: ' 仙人指路过路通 劝君任意走西东交易求财不费力，生意合伙也相通',
            book_all: ' 二人同心 其利断金 君子正心诚意与人和同之象',
            book_disease: ' 病轻 不久可愈 注意心脏，心肺等疾',
            book_name: '同人',
            book_introduc: '仙人指路 中吉卦',
            book_lucky: ' 如意吉祥 与人共事 上下皆和又得长辈提拔',
            id: 24,
            book_sort: '13',
            book_remark: '天火同人 乾上离下 二人同心之象 合作共事之意',
            book_result: ' 婚姻有成 行人归来 走失可见做事无差',
        },
        {
            book_action: ' 可圆满解决',
            book_love: ' 有情人终成眷属',
            book_lose: ' 找寻费时 惟可失而得',
            book_means: ' 砍对摸雀做事牢 是非口舌自然消婚姻合伙不费力 若问走失未脱逃',
            book_all: ' 太阳在天 遍照大地万物 但五阳争一阴须知有盈即缺',
            book_disease: ' 治疗可愈 防高血压 心脏头肺病患',
            book_name: '大有',
            book_introduc: '砍树摸雀上中卦',
            book_lucky: ' 得时得运 昌荣大吉 但防物极必反盛极而衰',
            id: 25,
            book_sort: '14',
            book_remark: '火天大有 离上乾下 日丽中天之象 好景不常之意',
            book_result: ' 恍惚不做 拿稳下手 若求名利至处自有',
        },
        {
            book_action: ' 宜速和解 拖延不利',
            book_love: ' 以谦诚之态度追求有成，可获良缘',
            book_lose: ' 难以发现 有失窃的可能',
            book_means: ' 天赐穷人一封金 不用争来二人分彼此分得金到手 一切谋望皆遂心',
            book_all: ' 山应在地面上 而今在地下代表谦逊之德',
            book_disease: ' 防旧病发，腹部或背部之疾 但仍属吉象',
            book_name: '谦',
            book_introduc: '二人分金 上平卦',
            book_lucky: ' 吉利平安 前途无限 但必须去除骄横之气',
            id: 26,
            book_sort: '15',
            book_remark: '地山谦 坤上艮下 空谷藏玉之象 虚怀处世之意。',
            book_result: ' 婚姻遂意 出外得地 交易合伙无不吉利',
        },
        {
            book_action: ' 有始而无终 易被多人连累破财 受惊',
            book_love: ' 一帆风顺 天赐良缘 但女方年龄比男方大',
            book_lose: ' 难以寻回',
            book_means: ' 青龙得意喜气生，谋望求财事有成，婚姻出行无阻碍 是非口舌的安宁',
            book_all: ' 雷出于地上 阳气奋发 万物欣欣向荣',
            book_disease: ' 凶险之卦 注意腹 腔 肝胆之疾',
            book_name: '豫',
            book_introduc: '青龙得位 上中卦',
            book_lucky: ' 如意安泰 可得长辈扶助 但须防色难凡事应有备而战',
            id: 27,
            book_sort: '16',
            book_remark: '雷地豫 震上坤下 雷奋大地之象 事见生机之意',
            book_result: ' 交易即成 行人即归 头绪有准合伙有利',
        },
        {
            book_action: ' 宜决意和解 目前无忧 但不久须防有祸',
            book_love: ' 防用情不专 沉迷情欲',
            book_lose: ' 即将疏忽之时 会突然察觉',
            book_lucky: ' 有去旧迎新之吉象 宜与人合作可获厚利 忌三心两意 或独断独行',
            book_means: ' 推车靠堰道路干，谋望求财不费难，婚姻出行无阻碍 疾病口舌保平安',
            book_all: ' 震木在兑泽之下 木必随水漂流随者 顺也',
            book_disease: ' 病重 须长期治疗 注意口腔肝 足患等症',
            id: 28,
            book_sort: '17',
            book_name: '随',
            book_remark: '泽雷随 兑上震下 乘马逐鹿之象 随遇而安之意',
            book_result: ' 苦极生荣 喜气盈盈 一切做事大运亨通',
        },
        {
            book_action: ' 慎防桃色纠纷 会拖一段时间不易解决',
            book_love: ' 苦恼多 受人诱惑 关系复杂切忌到处留情 徒增烦恼',
            book_lose: ' 找不回来，遗失似是木制工艺品 在门口或旅馆遗失 或者是寄失了',
            book_means: ' 卦中象如推磨 顺当为福反为祸心中有数事改变 凡事尽从忙里错',
            book_all: ' 风入山下 闭而不出 即物腐生虫意气不通 因循败事',
            book_disease: ' 宜把握治疗时机 冬季占得险象为内脏恶性疾病',
            book_name: '蛊',
            book_introduc: '推磨岔道 下吉卦',
            book_lucky: ' 诸事不如意 艰难迷惑 宜大胆革新否则引来内忧外患',
            id: 29,
            book_sort: '18',
            book_remark: '山风蛊 艮上巽下 物腐虫生之象 不进则退之意',
            book_result: ' 出行无益 行人未回 走失难见诸事莫为',
        },
        {
            book_action: ' 宜柔不宜刚 因本欲欺他人反伤自已',
            book_love: ' 柔顺者可行吉利 注意欲速则不达',
            book_lose: ' 不能立即发现 很久才能找回可能被埋在地下 是件会发声或震动的物件',
            book_means: ' 发政施仁志量高 出外求财任逍遥交易婚姻大有意 走失行人有信耗',
            book_all: ' 池泽之水灌溉地面万物 相辅相成，生生不息',
            book_disease: ' 病情较轻，为肠胃 口腔之疾 并防泌尿生殖系统病变',
            book_name: '临',
            book_introduc: '发政施仁 上平卦',
            book_lucky: ' 诸事亨通 上下和合 前途有望但不宜过于急进',
            id: 30,
            book_sort: '19',
            book_remark: '地泽临 坤上兑下 少女从母之象 循序渐进之意',
            book_result: ' 口舌消散 疾病即痊 求名称意家宅平安',
        },
        {
            book_action: ' 小人当道 愈争论惹纷争愈多但终会和解',
            book_love: ' 飘动不定 外表看好 但内里虚浮宜得长辈扶助',
            book_lose: ' 若能细心视察 可以找回来的',
            book_means: ' 鹊遇天晚宿林中 不知林内先有鹳虽然同处心生恶 卦外逢之事非轻',
            book_all: ' 风运行于坤地之上 喻有周游观览之意阴长阳消 正道衰微 万物难行',
            book_disease: ' 有渐恶化之象 病情变化多为腹 神经系统病症',
            book_name: '观',
            book_introduc: '颧鹊同林 下中卦',
            book_lucky: ' 处身于变化之中 宜多观察入微心身苦恼 并防外来诱惑',
            id: 31,
            book_sort: '20',
            book_remark: '风地观 巽上坤下 风扬尘埃之象 观察入微之意',
            book_result: ' 先难后易 谋事不易 交过节令忧愁变喜',
        },
        {
            book_action: ' 宜采取主动 据理力争',
            book_love: ' 有被人阻隔或横刀夺爱之象宜勇往直前',
            book_lose: ' 有被人捷足捡走的可能 寻回的机会不大',
            book_means: ' 运拙如同身受饥 幸得送饭又遇食适口充肠心欢喜 忧愁从此渐消移',
            book_all: ' 上唇与下唇间有物 必须咬断方能合拢 乃诸事被阻 务必去除 方可成功',
            book_disease: ' 病情严重 注意足部 心脏神经系统病变',
            book_name: '噬',
            book_introduc: '饥人遇食 中平卦',
            book_lucky: ' 诸事阻隔 纷争难免 宜守常规不为利诱 问题可解决',
            id: 32,
            book_sort: '21',
            book_remark: '嗑 火雷噬嗑 离上震下 喉中有物之象 夫妻怨怒之意',
            book_result: ' 见官有理 出门见喜 婚姻成全事事如意',
        },
        {
            book_action: ' 宜速求解决 不可拖延 可得贵人调解',
            book_love: ' 不宜单注重外表而忽略内涵不可自视太高',
            book_lose: ' 在家中遗失 将可寻回 不妨试试注意门脚的地方',
            book_means: ' 时来运转锐气周 窈窕淑女君子求钟古乐之大吉庆 占着此卦喜临门',
            book_all: ' 日落西山 照耀通明 华美灿烂同时喻光明力量渐消 阴暗的力量扩大',
            book_disease: ' 病情危重 为心脏 胸 腹等病',
            book_name: '贲',
            book_introduc: '喜气迎 中上卦',
            book_lucky: ' 表面风光风里空虚 必须充实自已凡事踏实 按部就班',
            id: 33,
            book_sort: '22',
            book_remark: '山火贲 艮上离下 争妍斗丽之象 粉饰妆粉之意',
            book_result: ' 出门吉祥 诸事顺当 失物见得月令高强',
        },
        {
            book_action: ' 因财而趣纷争 小人当道 宜避之则吉',
            book_love: ' 阴盛而阳衰 男追女则利 反之不利是非小人多',
            book_lose: ' 目前还隐藏在家中地上 可惜无法发现不久会被扫走',
            book_means: ' 花遇甘露旱逢河 生意买卖利息多婚姻自有人来助 出门永不受折磨',
            book_all: ' 山附于地喻山石崩落于地面上五阴迫一阳 正义被损',
            book_disease: ' 病情恶化之象 防头痛 肠胃性病等疾',
            book_name: '剥',
            book_introduc: '早莲逢河 上吉卦',
            book_lucky: ' 恶运缠身 宜重新部暑 不宜自作聪明防被女子及小人连累',
            id: 34,
            book_sort: '23',
            book_remark: '山地剥 艮上坤下 群阴剥阳之象 去旧生新之意',
            book_result: ' 占讼得利 占病即愈 占信见得谋事得意',
        },
        {
            book_action: ' 多人之事 但经多次扰攘才可解决',
            book_love: ' 性急则事败 缓可得成 有合可能',
            book_lose: ' 有失而得之可能',
            book_means: ' 若占此卦不相和 忧疑愁闲无定夺恩人无义以成怨 是非平地起风波',
            book_all: ' 雷在地中振发 喻春回大地一元始 万象更生',
            book_disease: ' 病防发 但可治 为肝 肠胃神经系统病变',
            book_name: '复',
            book_introduc: '人妻反目 中下卦',
            book_lucky: ' 开运亨通之象 万事不宜急进按部就班可成',
            id: 35,
            book_sort: '24',
            book_remark: '地雷复 坤上震下 万物更新之象 重修破旧之意',
            book_result: ' 寻人不见 心事不定 交节换月自然安宁',
        },
        {
            book_action: ' 因女人或死亡之事起纷争 宜和解否则招凶',
            book_love: ' 有不和 不顺遂或被伤害之凶象',
            book_lose: ' 找不到 似已遗失',
            book_means: ' 鸟如笼中难出头 占着此卦不自由谋望求财不定准 疾病忧犯口舌愁',
            book_all: ' 雷动于天 阳气舒发 为真实无虚妄之意',
            book_disease: ' 不宜意气用事 应尽力疗养为宜属呼吸系统 头足之疾病',
            book_name: '无妄',
            book_introduc: '鸟困牢笼 中下卦',
            book_lucky: ' 凡事宜守正 若行为不检者必招灾祸',
            id: 36,
            book_sort: '25',
            book_remark: '天雷无妄 乾上震下 石中蕴玉之象 守旧安常之意',
            book_result: ' 出门不遇 求财不利 婚姻走失疾病不宜',
        },
        {
            book_action: ' 因房地产引起 有破财之象但纠纷可解',
            book_love: ' 虽现时有小阻碍 但终可成功',
            book_lose: ' 有机会寻回 似是在圆形有盖盛存之物中',
            book_means: ' 忧愁常锁两眉间 千头万绪挂心间从今以后打开阵 任意而行不相干',
            book_all: ' 天之大而在山之中 以小阻大以阴畜阳为止为养',
            book_disease: ' 病虽重 但可治 防胸肺 腹或物部之病易积劳成疾',
            book_name: '大畜',
            book_introduc: '阵势得开 中吉卦',
            book_lucky: ' 处事不可好高骛远 宜脚踏实地可成大业 忌目空一切',
            id: 37,
            book_sort: '26',
            book_remark: '山天大畜 艮上乾下 浅水行舟之象 积小成大之意',
            book_result: ' 交节行人 出门大吉 好运有信百事和顺',
        },
        {
            book_action: ' 我告他人终不能成 宜速和解',
            book_love: ' 忌傲气凌人 宜重新估计对方之价值切勿因情误这青春',
            book_lose: ' 尽快去找 似被物件上下夹著',
            book_means: ' 文王访贤在渭滨 谋望求财事遂心交易出行方如意 疾病口舌可离身',
            book_all: ' 形如口腔之象 取其饮食之道须慎言 注重日常生活',
            book_disease: ' 占病为凶 久病者险 为肠胃咽喉 手足之疾',
            book_name: '颐',
            book_introduc: '渭水访贤 上吉卦',
            book_lucky: ' 处事欠缺周详考虑 不宜心怀阴谋要守正道而善方吉',
            id: 38,
            book_sort: '27',
            book_remark: '山雷颐 艮上震下 匣中藏剑之象 审慎交往之意',
            book_result: ' 渭水访贤 大吉大利 占着此卦好了运气',
        },
        {
            book_action: ' 有文书之烦 即使求和也未能如愿',
            book_love: ' 双方之眼光均太高或各已有心上人凶象',
            book_lose: ' 无法发现 不能物归原主',
            book_means: ' 夜梦金银醒来空 求名求利大不通婚姻难成交易散 走失行人不见踪',
            book_all: ' 中间四阳爻，为结实之梁 但初爻为阴爻 力弱不支 则势将摧折',
            book_disease: ' 严重 须耐心治疗 为肺 神经系统女占得妇科经带之疾',
            book_name: '大过',
            book_introduc: '夜梦金银 下下卦',
            book_lucky: ' 有力不从心 负担过重之象多烦恼 防官非及水险',
            id: 39,
            book_sort: '28',
            book_remark: '泽风大过 兑上巽下 枯木生花之象 反省过失之意',
            book_result: ' 月令不和 好事难谋 凡事忍耐休要琢磨',
        },
        {
            book_action: ' 有盗贼之讼 或田土之争 有理说不清凶象',
            book_love: ' 易沉弱于爱情中 但有险阻重重之象',
            book_lose: ' 找不回来 有失窃可能 或沉在水底因坎水有困难之意',
            book_means: ' 一路明月照水中 只见影儿不见踪愚人当财下去取 摸来摸去一场空',
            book_all: ' 两水重叠 坎水为险 进固险退亦险 进退两难',
            book_disease: ' 病重宜速治 否则难救 注意肾脏膀胱生殖器病',
            book_name: '坎',
            book_introduc: '水底捞月 下下卦',
            book_lucky: ' 危机重重 宜沉著应付 保持心境开朗凡事莫与人争',
            id: 40,
            book_sort: '29',
            book_remark: '坎为水 坎上坎下 重重险陷之象 向下内敛之意',
            book_result: ' 求名不遂 疾病未愈 婚姻未成合伙不利',
        },
        {
            book_action: ' 只宜人侵已 不宜已侵入 主动者不利',
            book_love: ' 不宜性急 会弄巧反拙 静而诚者必有所成',
            book_lose: ' 动作快 可寻回',
            book_means: ' 占此卦者遇天宫 富禄必然降人间一切谋望皆吉庆 愁闲消散主平安',
            book_all: ' 只宜人侵已 不宜已侵人 主动者不利',
            book_disease: ' 急病可解 久病刚凶 宜耐心调养为心脏眼科血疾',
            book_name: '离',
            book_introduc: '天官赐福 上上卦',
            book_lucky: ' 外观极盛 烈日当空之象 火有气但无形 主不实不定之意',
            id: 41,
            book_sort: '30',
            book_remark: '离为火 离上离下 丽日当天之象 光明远大之意',
            book_result: ' 月令皆善 诸事方便 出门见喜灾消病散',
        },
        {
            book_action: ' 提防桃色纠纷 诸事宜和解有贵人相助',
            book_love: ' 正常恋情 则发展顺利 但名不顺者当悬崖勒马',
            book_lose: ' 尽速找回 可以取回 延误时机则找不回来',
            book_means: ' 脚踏棒槌转悠悠 时运不来莫强求幸喜今日时运转 自有好事在后头',
            book_all: ' 少男在少女之下 彼此感应象征新婚 两性交感',
            book_disease: ' 防泌尿系统病 肠胃病及性病等须疗养得法 否则不利',
            book_name: '咸',
            book_introduc: '萌芽出土 平平卦',
            book_lucky: ' 如意吉祥 但勿为不正当感情而意乱神迷',
            id: 42,
            book_sort: '31',
            book_remark: '泽山咸 兑上艮下 山泽通气之象 往来无阻之意',
            book_result: ' 谋望有成 出门可行 走失有信疾病安宁',
        },
        {
            book_action: ' 小人招祸 但宜速战速决 不利拖延宜和解',
            book_love: ' 万事亨通 恒久如意 终成美眷',
            book_lose: ' 不能寻回',
            book_means: ' 鱼来撞网乐自然 卦占行人不久还交易婚姻两成就 谋望求财不费难',
            book_all: ' 震者为动 宜向外发展 巽为入为内向一内一外 各居本位 故能永恒不变 喻夫妇之道',
            book_disease: ' 为慢性及须长期治疗之疾 注意肝之疾',
            book_name: '恒',
            book_introduc: '鱼来掩网 上平卦',
            book_lucky: ' 万事亨通 能恒久努力 安守本份则吉妄动则招灾',
            id: 43,
            book_sort: '32',
            book_remark: '雷风恒 震上巽下 相对并行之象 努力不懈之意',
            book_result: ' 出行凑巧 有病就好 虽有口舌自然消了',
        },
        {
            book_action: ' 强行争取亦不利 宜罢手逃避反吉',
            book_love: ' 落花虽有意 流水却无情',
            book_lose: ' 失落远处 不能寻回',
            book_means: ' 浓云遮日不光明 劝君切莫远出行婚姻求财皆不吉 须防口舌到门庭',
            book_all: ' 者遁也 山在天之下 阴渐长而阳渐消 宜退避三舍',
            book_disease: ' 病重 注意血气不调 头 背筋骨良之疾',
            book_name: '天山遁',
            book_introduc: '浓云蔽日 中平卦',
            book_lucky: ' 小人道长 君子道消 凡事宜退不宜进穷则独善其身 养诲修身',
            id: 44,
            book_sort: '33',
            book_remark: '乾上艮下 守旧去恶之象 掘井无泉之意',
            book_result: ' 占病不安 讼事见官 功名不成事不遂心',
        },
        {
            book_action: ' 忌与人斗气 宜和解收场否则两败俱伤',
            book_love: ' 只要保持仁和谦恭 则有成果否则易招么悔',
            book_lose: ' 不能取回',
            book_means: ' 卦占工师得大木 眼前该着走上路时来运转多顺当 有事自管放心做',
            book_all: ' 雷声响亮 光明天际 为正大光明之象又为强烈地动之象 为六冲卦之一',
            book_disease: ' 生平少病者遇此卦则不利 注意急性呼吸道感染和脑疾等',
            book_name: '大壮',
            book_introduc: '工师得木 上平卦',
            book_lucky: ' 动势虽强 但已届极盛之时宜心平气和 否则么招失败 须知物极必反',
            id: 45,
            book_sort: '34',
            book_remark: '雷天大壮 震上乾下猛处生角之象 声威大壮之意',
            book_result: ' 出门吉利 口舌远避 疾病皆除行人即至',
        },
        {
            book_action: ' 最终能圆满解决',
            book_love: ' 以柔顺态度追求 定可成功',
            book_lose: ' 动作快 可以寻回来 似是在地上的箱子之类藏着',
            book_means: ' 锄地得金苗里草 谁想财帛将人找谋望求财皆如意 这个运气也算好',
            book_all: ' 日出地面 普照大地 有光明上进之象',
            book_disease: ' 久病者凶 近病无妨 注意胃肠心脏之疾',
            book_name: '晋',
            book_introduc: '锄地得金 上平卦',
            book_lucky: ' 事业 名望 财运皆吉 所谓有加官晋爵之兆',
            id: 46,
            book_sort: '35',
            book_remark: '火地晋 离上坤下 满地锦绣之象 良臣遇君之意',
            book_result: ' 进退两难 不敢强辩 拨云见日该你出现',
        },
        {
            book_action: ' 败象 宜和解了事 愈争愈苦',
            book_love: ' 对方不接受自已 难得成功',
            book_lose: ' 不能立即寻回 正当要遗忘这件事时，会意外有所发现',
            book_means: ' 时乖运拙走不着 急忙过河拆了桥恩人无义反为怨 凡事无功枉受劳',
            book_all: ' 太阳掩没在坤地之下 大地黑暗有失明之象',
            book_disease: ' 凶象 为潜伏已久之疾 注意心脏腹部之疾或神经病',
            book_name: '明夷',
            book_introduc: '过河拆桥 下平卦',
            book_lucky: ' 百事阻滞 小人加害 遇事多迷惑宜守 静待时机而动',
            id: 47,
            book_sort: '36',
            book_remark: '地火明夷 坤上离下 凤凰垂翼之象 弃暗投明之意',
            book_result: ' 行人未至 头绪不清 口舌紧避凡事小心',
        },
        {
            book_action: ' 虽产生大疑虑 若行事合理则无碍',
            book_love: ' 大吉之象 终成美眷',
            book_lose: ' 出现 隐藏在家中 可能是被家人收起来了',
            book_means: ' 镜里观花休认真 谋望求财不遂心交易慢成婚姻散 走失行人无音信',
            book_all: ' 风吹火之象 助火之威 喻家人同心协力发展事业',
            book_disease: ' 注意心脏或胆病 必须小心调理',
            book_name: '家人',
            book_introduc: '镜里观花 下下卦',
            book_lucky: ' 平安本吉 与人合作则易成更有喜庆之象 如添丁婚嫁等',
            id: 48,
            book_sort: '37',
            book_remark: '风火家人 巽上离下 人海求珠之象 开花结果之意',
            book_result: ' 找人不遇 疾病未愈 求名不准官事不宜',
        },
        {
            book_action: ' 宜速求和解 迟则理屈辞穷',
            book_love: ' 互相皆无意 不宜寄望',
            book_lose: ' 不能找回 有失窃可能',
            book_means: ' 路上行人色匆匆 过河无桥遇薄冰小心谨慎过得去 一步错了落水中',
            book_all: ' 离火向上 兑泽则向下 一上一下两相乖违 又二女同居 不得正之象',
            book_disease: ' 轻症宜速就医 重症则危 更防断症错误注意心脏 寒热失调之症',
            book_name: '睽',
            book_introduc: '行走薄冰 下平卦',
            book_lucky: ' 气运欠佳 诸事难成 有水火不容之象宜处变不惊',
            id: 49,
            book_sort: '38',
            book_remark: '火泽睽 离上兑下 二女同居之象 阳阴失调之意',
            book_result: ' 薄冰甚险 行人难禁 若占此卦凡事小心',
        },
        {
            book_action: ' 终必有险 更防血光 不宜起讼动则招咎',
            book_love: ' 困难重重 破象已现',
            book_lose: ' 搜索有困难阻滞而停止 不能寻回',
            book_means: ' 大雨倾地雪满天 路上行人苦又难拖泥带水费尽力 事不遂心且耐烦',
            book_all: ' 前路险陷 后有高山 进退维谷如跛者举步为艰',
            book_disease: ' 病重 不可疏忽医治 注意肾胃 手部四肢损伤',
            book_name: '蹇',
            book_introduc: '雨雪载途 下下卦',
            book_lucky: ' 多灾多难 进退两难 此时宜守正道不可轻举妄动 动反招祸',
            id: 50,
            book_sort: '39',
            book_remark: '水山蹇 坎上艮上 门前有陷之象 背明向暗之意',
            book_result: ' 行人未至 投向无门 好事难成求名不准',
        },
        {
            book_action: ' 一般纠纷皆可解决 宜中当机立断不可拖延',
            book_love: ' 无须犹疑 把握良机 可成功',
            book_lose: ' 遗失之物似有被支解破坏的可能故寻回的机会不大',
            book_means: ' 五关脱难运抬头 劝君须当把财求交易出行有人助 疾病口舌不用愁',
            book_all: ' 春雷大作 大地解冻 喻冬去春来生机再现',
            book_disease: ' 久病可治愈 注意肝 肾 足疾',
            book_name: '解',
            book_introduc: '五关脱难 中吉卦',
            book_lucky: ' 宜把握良机快速处理身边困境更宜出外求谋因贵人在远方以西南为吉方',
            id: 51,
            book_sort: '40',
            book_remark: '雷水解 震上坎下 草木舒展之象 遇困可解之意',
            book_result: ' 疾病大好 行人来早 谋望成全诸般凑巧',
        },
        {
            book_action: ' 有斗争之象 损失破财 和解反而获利益',
            book_love: ' 不利女性之卦 以诚信待人可得成功 不宜斤斤计较',
            book_lose: ' 不能寻回',
            book_means: ' 时运不至费心多 比作推车受折磨山路崎岖掉了耳 左插右安安不着',
            book_all: ' 山高水深 各得其所 因损得益之象',
            book_disease: ' 现况病情虽重 积极治疗可愈身体较衰弱 注意肠胃 咽喉 贫血等疾',
            book_name: '损',
            book_introduc: '推车掉耳 下中卦',
            book_lucky: ' 现况诸事不顺 有破财之象虽先损失 但后反而得益 因祸得福',
            id: 52,
            book_sort: '41',
            book_remark: '山泽损 艮上兑下 山高水深之象 以德报怨之意',
            book_result: ' 时运不遂 不可胡为 交节换月自然夺魁',
        },
        {
            book_action: ' 有牢狱之灾 或事因女人 房地产引起宜和解',
            book_love: ' 相亲相爱 良缘天定',
            book_lose: ' 有望可寻回',
            book_means: ' 时来运转喜气发 多年枯木又开花枝叶重生多茂盛 几人见了几人夸',
            book_all: ' 强风配快雷 声威增长之象长男配长女 夫妇合体 增益儿子之象',
            book_disease: ' 可治愈 提防肝胆 肠胃之疾或性病等',
            book_name: '益',
            book_introduc: '枯木开花 中吉卦',
            book_lucky: ' 现在当吉运 可得贵人之助而成功宜施惠于人 施比受更有福',
            id: 53,
            book_sort: '42',
            book_remark: '风雷益 巽上震下 风雷交错之象 损上益下之意',
            book_result: ' 交易有成 见官有理 走失得见出门见喜',
        },
        {
            book_action: ' 不宜与人争执 因势孤力弱宜寻求法律途径解决',
            book_love: ' 决裂之象但多为男方摒弃女方之象',
            book_lose: ' 相信失物已经损坏 不能寻回',
            book_means: ' 游蜂脱网喜无边 添财进口福禄连外则通达内则顺 富贵荣华胜以前',
            book_all: ' 泽水积满而泛滥成灾 滔天之势又五阳爻之盛势必除去唯一阴爻 故一阴独立',
            book_disease: ' 病情重宜速治 防头部 呼吸系统肿瘤等疾',
            book_name: '夬',
            book_introduc: '游蜂脱网 中吉卦',
            book_lucky: ' 目前虽吉 但困难及变动正在蕴酿中宜提高警觉 忌骄傲 防口舌是非',
            id: 54,
            book_sort: '43',
            book_remark: '泽天夬 兑上乾下 蛟龙登天之象 亏中有益之意',
            book_result: ' 词讼了结 疾病除根 求财到手任意遂心',
        },
        {
            book_action: ' 提防桃色纠纷 是非谣言播弄',
            book_love: ' 双方互不满意 感情复杂 用情不专之象',
            book_lose: ' 尽快寻找 可失而得 失物似被重重物件压在最底部',
            book_means: ' 他乡遇友喜气欢 须知运气福重添自今交了顺当运 向后保管不相干',
            book_all: ' 风无孔不入 所吹到之处 暴露其间之物体无一不与之相遇 为邂逅之意',
            book_disease: ' 病情重 有恶化情况 注意泌尿生殖系统胸肺科病',
            book_name: '姤',
            book_introduc: '他乡遇发 上平卦',
            book_lucky: ' 阳长阴消 注意桃色纠纷 诸事阻滞慎重行事',
            id: 55,
            book_sort: '44',
            book_remark: '天风姤 乾上巽下 风云际会之象 聚散随缘之意',
            book_result: ' 功名有成 家宅平安 失物得见占病无妨',
        },
        {
            book_action: ' 宜解不宜结',
            book_love: ' 可喜可贺之象',
            book_lose: ' 多半能失而复得',
            book_means: ' 鲤鱼化龙喜气来 口舌疾病永无灾愁疑从此都消散 祸门闭来福门开',
            book_all: ' 泽在地上 水聚于泥土中 滋养草木生长茂盛',
            book_disease: ' 凶象 宜速诊治 防胸腹及咽喉之病变',
            book_name: '萃',
            book_introduc: '鲤鱼化龙 中吉卦',
            book_lucky: ' 吉运昌盛 又得长辈提携 事业大利但须防财务纠纷',
            id: 56,
            book_sort: '45',
            book_remark: '泽地萃 兑上坤上 鲤登龙门之象 精英荟萃之意',
            book_result: ' 鲤鱼化龙 喜气重重 求财到手做事有功',
        },
        {
            book_action: ' 宜持平和态度处理 可争取主动胜算在握',
            book_love: ' 可望成功 但不宜急进',
            book_lose: ' 不易寻回 失物有被束之高阁的可能',
            book_means: ' 指日离升气象新 走失行人有音信功名出行遂心好 疾病口舌皆除根',
            book_all: ' 树木从地上不断向上 有进升之势',
            book_disease: ' 病情重 注意腹部 胆管之疾',
            book_name: '升',
            book_introduc: '指日高升 上吉卦',
            book_lucky: ' 名利双收 发展开运之象 宜向南方发展',
            id: 57,
            book_sort: '46',
            book_remark: '地风升 坤上巽下 积小成大之象 拼搏得益之意',
            book_result: ' 求财到手 谋事可成 寻人得见家宅安宁',
        },
        {
            book_action: ' 凡事不宜过于执著 虽防牢狱之灾',
            book_love: ' 多失败收场 难成气候',
            book_lose: ' 不能寻回',
            book_means: ' 时运不来有人欺 千方百计费商议明明与你说好话 撮上杆去抽了梯',
            book_all: ' 不在泽下 万物不生 喻君子困穷小人滥盈',
            book_disease: ' 危重之象 注意口腔咽喉 泌尿系统甚至性病',
            book_name: '困',
            book_introduc: '撮杆抽梯 下平卦',
            book_lucky: ' 诸事不如意 所谓龙游浅遭虾戏',
            id: 58,
            book_sort: '47',
            book_remark: '泽水困 兑上坎下 河中无水之象 守正待机之意',
            book_result: ' 当交君子 莫听小人 凡事谨慎永不受穷',
        },
        {
            book_action: ' 有刑罚之象 且受人牵连 及防房地产之诉讼',
            book_love: ' 形势不大理想 有分开再合之象故往后可成',
            book_lose: ' 不能寻回',
            book_means: ' 枯井破了已多年 一朝涌泉出水新资生济渴人称羡 时来运转乐自然',
            book_all: ' 水被植物吸收 滋养树身又象征汲器入井取水有节约重覆之意',
            book_disease: ' 病情较重且拖延 可能是复发',
            book_name: '井',
            book_introduc: '枯井生泉 上中卦',
            book_lucky: ' 井为静物不能移动故凡事不能进取主动又缺乏冲劲不如处之泰然更有利',
            id: 59,
            book_sort: '48',
            book_remark: '水风井 坎上巽下 珠藏深渊之象 井井有条之意',
            book_result: ' 精神渐爽 富禄日增 出入皆吉百事亨通',
        },
        {
            book_action: ' 更改变旧有对策 才可圆满解决',
            book_love: ' 代表往事如烟 重新再开始或应改旧有态度',
            book_lose: ' 因有弃旧迎新之意 故相信不能寻回',
            book_means: ' 苗逢旱天渐渐衰 幸得天恩降雨来忧去喜来能变化 求谋诸事遂心怀',
            book_all: ' 兑为金 被离火所烧 变革之象',
            book_disease: ' 病情多变 宜改换求医方法注意心脏 眼目和咽喉之疾',
            book_name: '革',
            book_introduc: '毕曲得雨 上平卦',
            book_lucky: ' 凡事均在变动之中 宜去旧立新以应革新之象',
            id: 60,
            book_sort: '49',
            book_remark: '泽火革 兑上离下 豹变为虎之象 改旧纳新之意',
            book_result: ' 出行大吉 走失能找 行人来信百般凑巧',
        },
        {
            book_action: ' 由小事引起 宜和解了事',
            book_love: ' 未婚者则顺利 已婚女性占得防婚外情影响家庭',
            book_lose: ' 过一段时间后可寻回 惟已变形',
            book_means: ' 若占此卦喜自然 求名求利两周全婚姻合伙皆如意 生意兴隆乐自然',
            book_all: ' 木之上有离火 为燃炊烹饪之象鼎有去旧立新 改过迁善之意',
            book_disease: ' 病情有变 但无大碍 为胆石心脏 消化系统病',
            book_name: '鼎',
            book_introduc: '渔人得利 上中卦',
            book_lucky: ' 时运仍佳 事业可成 但诸事不宜迟滞及防有诉讼之累',
            id: 61,
            book_sort: '50',
            book_remark: '火风鼎 离上巽下 鼎器烹调之象 去故取新之意',
            book_result: ' 出门有益 交易可成 官事无妨诸事安宁',
        },
        {
            book_action: ' 反覆难平 宜收敛脾气 心平气和',
            book_love: ' 是非 纷乱 虚而无实之象',
            book_lose: ' 可能是受某些事惊吓而遗失令你惊惶失措 尝试于会发声的东西或电器处寻找',
            book_means: ' 占者逢之撞金钟 时来运转响一声谋事求财不费力 交易合伙大亨通',
            book_all: ' 重雷发向 千里传声 有惊无险之象亦有变动之意',
            book_disease: ' 注意肝 神经系统 足疾 病情反覆',
            book_name: '震',
            book_introduc: '金钟夜掸 中吉卦',
            book_lucky: ' 表面昌盛风光 内里正处多事之秋动荡不安之意',
            id: 62,
            book_sort: '51',
            book_remark: '震为雷 震上震下 雷惊百里之象 惊恐不屈之意',
            book_result: ' 求名遂意 做事遂心 走失行人自然有音',
        },
        {
            book_action: ' 因小事而化大 宜速求和 忌土姓人',
            book_love: ' 有单恋不和之象 双方阻隔重重关系停滞不前',
            book_lose: ' 可以寻回 但要等一段时间藏在家中 旅馆 寺院 山中某处',
            book_means: ' 矬巴勾枣难捞枝 交易寻人不投机谋望求财最费力 婚姻合伙终是虚',
            book_all: ' 两重高山并峙 故宜止不宜进阻塞之象',
            book_disease: ' 难治 注意肠胃血管硬化及结核病',
            book_name: '艮',
            book_introduc: '矬巴勾枣 下中卦',
            book_lucky: ' 凡事不宜妄动 前路受阻 只好待机而动',
            id: 63,
            book_sort: '52',
            book_remark: '艮为山 艮上艮下 重山关锁之象步步为营之意',
            book_result: ' 好事难成 走失难寻 凡事谨慎交节安宁',
        },
        {
            book_action: ' 宜进不宜退 据理力争可胜',
            book_love: ' 循序发展 可成功 但婚姻有再娶之象',
            book_lose: ' 多数不能寻回',
            book_means: ' 凤凰落在西岐山 长鸣几声出圣贤天降文王开基业 富贵荣华八百年',
            book_all: ' 山上种有树木 逐渐成长 比喻循序渐进',
            book_disease: ' 恶化之象 注意胃 肠 背痛等',
            book_name: '渐',
            book_introduc: '凤鸣岐山 上上卦',
            book_lucky: ' 逐渐走向光明前途 凡事宜打根基可得吉庆 但须防色情之难及文书错失',
            id: 64,
            book_sort: '53',
            book_remark: '风山渐 巽上艮下 草木渐茂之象 积小成多之意',
            book_result: ' 出门有益 求财必准 疾病皆除诸事平稳',
        },
        {
            book_action: ' 事牵连于女性 宜力求和解但我方必有损失',
            book_love: ' 有女追男之象 但多为悲剧收场宜三思而后行',
            book_lose: ' 失物虽有归还的可能 但自身仍有损失',
            book_means: ' 求鱼须当向水中 树上求之不顺情受尽爬揭难遂意 劳而无功事不成',
            book_all: ' 震长男在上兑少女在下 女必归从归即是出嫁但少女配长男 非正常组合',
            book_disease: ' 病危重 极易恶化 为中风肝病 气管及性病等',
            book_name: '归妹',
            book_introduc: '缘木求鱼 下平卦',
            book_lucky: ' 处事有违常理正道 先得其益但随后祸事百端',
            id: 65,
            book_sort: '54',
            book_remark: '雷泽归妹 震上兑下 少女追男之象 错失端正之意',
            book_result: ' 月令不好 做事颠倒 打算到手遂心的少',
        },
        {
            book_action: ' 自已虽势如破竹 胜券在握但应留一线',
            book_love: ' 吉利有成 但不可得意忘形',
            book_lose: ' 尽快找寻 可失而得',
            book_means: ' 古镜昏暗好几年 一朝磨明似月圆君子谋事占此卦 时来转乐自然',
            book_all: ' 雷电交加 声势壮大 又离日动于天际普照大地 皆为盛大之象',
            book_disease: ' 病况重 注意肝足疾及因压心脏等疾',
            book_name: '丰',
            book_introduc: '古镜重明 中吉卦',
            book_lucky: ' 运势极强 为收获之时 但不宜贪得无厌须知足常乐 要防是非 损财甚至火险',
            id: 66,
            book_sort: '55',
            book_remark: '雷火丰 震上离下 光明普照之象 弃暗投明之意',
            book_result: ' 出行有益 交易得利 疾病好转求名如意',
        },
        {
            book_action: ' 宜速战速决 时间一拖则不利',
            book_love: ' 呈现不稳定现象 有孤身上路之叹宜检讨原因',
            book_lose: ' 尽快去找 应可寻回失物似在屋舍之外留意镜子之类的物体',
            book_means: ' 飞鸟树上筑高巢 小人使计用火烧如占此卦大不利 一切谋望枉徒劳',
            book_all: ' 火烧山野 火头遍布所到之处无一幸免 火头尤如行旅之人 无所定处',
            book_disease: ' 病情变化不定 宜速就医',
            book_name: '旅',
            book_introduc: '宿鸟焚巢 下下卦',
            book_lucky: ' 诸事变动不定 此时只好坚守信心多参考他人意见 否则必有凶',
            id: 67,
            book_sort: '56',
            book_remark: '火山旅 离上艮下 鸟焚其果之象 乐极生悲之意',
            book_result: ' 求财费力 行人未还 走失无信找事也难',
        },
        {
            book_action: ' 不易和解 但一方肯让步则易解决',
            book_love: ' 有不稳定之象 宜作真诚沟通不可一味奉承',
            book_lose: ' 遗失在远处 不能寻回',
            book_means: ' 泛舟得水离沙滩 出外行人早回家是非口舌皆无碍 婚姻合伙更不差',
            book_all: ' 此卦为两重巽风重叠巽为入风之所到无孔不入 尤如政令颁布 深入民心',
            book_disease: ' 六冲卦者久病则凶 且病情变化多端',
            book_name: '巽',
            book_introduc: '孤舟得水 中吉卦',
            book_lucky: ' 波折重重 运势起落浮沉不定要随机应变 心平气和 择善固执',
            id: 68,
            book_sort: '57',
            book_remark: '巽为风 巽上巽下 飓风覆船之象 上行下效之意',
            book_result: ' 功名称意 求财得利 交易可成疾病痊愈',
        },
        {
            book_action: ' 似为两个女性及金钱之事惹起宜有和事佬出面调解',
            book_love: ' 可能因金钱而致口舌之争 又或者因两个女性而烦恼',
            book_lose: ' 遗失物似为金属或金钱 有望失而得但是迟一点 且多数已损毁或损失',
            book_means: ' 这个卦象真有趣 觉着做事不费力休要错过这机会 事事就觉遂心意',
            book_all: ' 两泽相依 更得泽中映月 美景良辰令人怡悦',
            book_disease: ' 六冲之卦久病则凶 注意生活检点戒酒色',
            book_name: '兑',
            book_introduc: '趁水和泥 中吉卦',
            book_lucky: ' 悲喜交集 有誉有讥 守正道诸事尚可称意',
            id: 69,
            book_sort: '58',
            book_remark: '兑为泽 兑上兑下 天降雨泽之象 有誉有讥之意',
            book_result: ' 口舌消散 疾病痊愈 求财到手谋事遂心',
        },
        {
            book_action: ' 凡事大事化小 小事化无 诉讼可解',
            book_love: ' 现时有障碍 但最终能圆满',
            book_lose: ' 不能寻回',
            book_means: ' 隔河望见一锭金 欲取河宽水又深指望钱财难到手 日夜思妄费心',
            book_all: ' 风吹在水面上 流动四散 又有春风吹散严寒令冰雪消解',
            book_disease: ' 幼年多体弱多病 及年逐长大而渐康注意血液 内分泌',
            book_name: '涣',
            book_introduc: '隔河望金 下下卦',
            book_lucky: ' 虽有忧患 但终可解困 百事亨通忌任性散慢',
            id: 70,
            book_sort: '59',
            book_remark: '风水涣 巽上坎下 顺风扬帆之象 随波遂流之意',
            book_result: ' 婚姻不济 合伙无利 交易出行总不如意',
        },
        {
            book_action: ' 局事僵持不下 宜让则可解',
            book_love: ' 男女正常交往则吉利 相反则凶',
            book_lose: ' 不能寻回',
            book_means: ' 时来运转喜气生 登台封神姜太公到此诸神皆退位 纵然有祸不成凶',
            book_all: ' 泽为池沼 坎水在上 喻蓄积及约束水份不使流失但水位过高 则成泛滥',
            book_disease: ' 注意泌尿系统消化系病变 宜速就医',
            book_name: '节',
            book_introduc: '斩将卦神 上吉卦',
            book_lucky: ' 有志不能伸 诸事必须节制不宜过份 更要戒酒色',
            id: 71,
            book_sort: '60',
            book_remark: '水泽节 坎上兑下 蓄水成塘象 勤检克己之意',
            book_result: ' 月令高强 声名大扬 走失有信官事不妨',
        },
        {
            book_action: ' 为突发事件 宜把握第一时间处理迟则反凶',
            book_love: ' 双方能以诚相待 良缘可定',
            book_lose: ' 可失而得 但需要一段时间',
            book_means: ' 此卦占之运气歹 如同太公做买卖贩猪羊快贩牛迟 猪羊齐贩断了宰',
            book_all: ' 中孚为诚信意 风吹在泽水之上泽水必相应而起波浪 为共鸣之象',
            book_disease: ' 金木交战之象 士妥井啁理注意腹脾胃',
            book_name: '中孚',
            book_introduc: '贩卖猪羊 下下卦',
            book_lucky: ' 凡事以 诚 待人 以 信处事则诸事皆吉 必存邪念则凶',
            id: 72,
            book_sort: '61',
            book_remark: '风泽中孚 巽上兑下 鹤鸣子和之象 以诚待人之意',
            book_result: ' 占名不利 占利不全 疾病不愈做事更难',
        },
        {
            book_action: ' 不宜各走极端 宜多沟通和解',
            book_love: ' 相处有障碍 虽可成功但最终又不和',
            book_lose: ' 不能寻回',
            book_means: ' 行人路过独木桥 心内惶恐眼里跳爽利保保过得去 慢行一步不安牢',
            book_all: ' 山上有雷 雷声虽大但被山阻隔雷声减弱 即为 小过',
            book_disease: ' 病情有恶化之象 但及时诊治则吉防手足 肠胃之疾',
            book_name: '小过',
            book_introduc: '急过独桥 中平卦',
            book_lucky: ' 诸事不利 宜行小事 不宜做大事更防因小过失做成惊动 惹来是非争讼',
            id: 73,
            book_sort: '62',
            book_remark: '雷山小过 震上艮下 飞鸟遗音之象 阳奉阴违之意',
            book_result: ' 求财到手 官事平常 目下不吉交节自强',
        },
        {
            book_action: ' 有理说不清 仍须把握最有利时机争取主动迟则反见凶',
            book_love: ' 初则出双入对 形影不离 但日久反目离异',
            book_lose: ' 应可寻回',
            book_means: ' 金榜之上提姓名 不负当年苦用功人逢此卦多吉庆 一切谋望大亨通',
            book_all: ' 坎水在离火之上 水性下注火势上炎 水火相济 完成之意',
            book_disease: ' 短期虽有好转 但好景不长',
            book_name: '既济',
            book_introduc: '金榜提名 上中卦',
            book_lucky: ' 名利双收 成功之象 防物极必反初吉后凶',
            id: 74,
            book_sort: '63',
            book_remark: '水火既济 坎上离下 阴阳和谐之象 上下相通之意',
            book_result: ' 月令吉善 找人寻见 走失能找口舌消散',
        },
        {
            book_action: ' 宜拖延时间 日久可得贵人之助和解了事',
            book_love: ' 发展初期难以沟通 格格不入但必须耐心 慢慢会得到对方接受',
            book_lose: ' 不能寻回',
            book_means: ' 太岁入运事多愁 婚姻财帛莫强求交易出门走见吉 走失行人不露头',
            book_all: ' 水性下注 火势向上 水火不交阴阳不得正位 未能完成和未能成功之意',
            book_disease: ' 病情不稳定 注意心肾不交失眠 血液等病',
            book_name: '未济',
            book_introduc: '太岁月健 中平卦',
            book_lucky: ' 运气欠佳 但必须耐心突破难关终可成功 有初凶后吉之象',
            id: 75,
            book_sort: '64',
            book_remark: '火水未济 离上坎下 阴阳失调之象 上下不通之意',
            book_result: ' 官讼不吉 口舌有灾 目下忍耐过月无妨',
        },
    ];
};
